# Generated by Django 3.2.7 on 2021-12-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_api'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodata',
            options={},
        ),
    ]
