# Generated by Django 3.2.7 on 2021-12-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_biodata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodata',
            options={'verbose_name_plural': 'Biodata'},
        ),
    ]
