# Generated by Django 3.2.7 on 2021-12-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_biodata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodata',
            options={'verbose_name_plural': 'Api'},
        ),
    ]
